name: pyunhai_woondng_demo
description: Demonstrates how to use the video_player plugin.
version: 0.0.1
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  video_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    path: ../../../integration_test
  pedantic: ^1.8.0
  test: ^1.15.7


flutter:
  uses-material-design: true
  assets:
   - assets/PushUpEditedLow.mp4

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
